### PR TITLE
Deploy to Heroku through GitHub WFLs

### PR DESCRIPTION
**Pull request by FindNew0**
Since your direct heroku deployment link is getting banned again and again thought it might be useful.
Please don't kill me

### CODE REVIEW

**Comment by ForbiddenLinkers** [comment]
Will not work for all users. This will work for 1 person per repo

**Comment by New-dev0** [comment]
Thanks for your pull request, but we cant accept it. 
This method work only for people having Github Account (probably only Individuals).
And even we cant support this officially! 

If you will like to spread the method, you can share it with friends or other ultroid users, with your repo ;)

**Comment by FindNew0** [comment]
> This method work only for people having Github Account (probably only Individuals).
I appreciate your reply. But thus method can be used for individuals who have a GitHub account and as for deployment ez every step is specified.
> And even we cant support this officially!
I am just asking to add it as an alternative to app.json method. As it is getting banned from time to time. So imo it can be quite helpful :) 😄

**Comment by FindNew0** [comment]
> Thanks for your pull request, but we cant accept it.
> This method work only for people having Github Account (probably only Individuals).
> And even we cant support this officially!
> 
> If you will like to spread the method, you can share it with friends or other ultroid users, with your repo ;)

I appreciate your reply. But thus method can be used for individuals who have a GitHub account and as for deployment ez every step is specified.

**Comment by FindNew0** [comment]
> This method work only for people having Github Account (probably only Individuals).

I appreciate your reply. This method can be used for individuals who have a GitHub account and as for deployment it is very easy as every step is specified.

> And even we cant support this officially!

I am not asking you to remove app.json method. But heroku keeps on suspending the accounts made through direct deployment. So thought this could be a good alternative.

**Comment by xditya** [comment]
This still wouldn't work - the GitHub actions you've used utilises heroku's api to deploy, which would just throw an error:
`{"id":"aup_violation","message":"We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy."}`

Have you tried deploying using this workflow before?

**Comment by FindNew0** [comment]
Yes I've

**Comment by FindNew0** [comment]
Ya so ppl who fork keep to themselves only ig
And after deploy they can change things like secrets and deploy for another
person

**Comment by New-dev0** [comment]
@FindNew0 Just a suggestion
Please dont reply from email/gmail application..

**Comment by FindNew0** [comment]
> Have you tried deploying using this workflow before?

Yes I've

**Comment by FindNew0** [comment]
> @FindNew0 Just a suggestion Please dont reply from email/gmail application..

sorry for that won't happen again

**Pull request closed without merging**
