### PR TITLE
Gladiator 007 patch 1

### PR DESCRIPTION
**Pull request by Gladiator-007**

### CODE REVIEW

**Comment by Gladiator-007** [comment]
my bad

**Comment by amitkr-codes** [comment]
@Gladiator-007 OP work
Wait for DMCA

**Comment by Gladiator-007** [comment]
Sorry, That was my fault...
I was merging that to my branch

**Comment by Gladiator-007** [comment]
By mistake I sent that req to main ultroid branch. 😢😥

**Comment by amitkr-codes** [comment]
@Gladiator-007 Ooo I see
Still DMCA coming for violating license

**Comment by Gladiator-007** [comment]
How?

**Comment by Gladiator-007** [comment]
@buddhhu I forked repo and have a look at my readme file...

**Comment by Atul-Kumar-Jena** [comment]
Either fork then edit else make it private and use urself only..else
DMCA🤣🤣

**Comment by Gladiator-007** [comment]
@hellboi-atul I forked and then edited that only.... 😇

**Comment by amitkr-codes** [comment]
@Gladiator-007 U still violate the copyright license which was in every file
It's on you revert/private/delete your repo or let github handle themselves

**Comment by Gladiator-007** [comment]
@buddhhu I used github workflows to change because my forked repo was not working... 😢😓

Wait let me make my repo private.. 
Sorry 😥

**Comment by Gladiator-007** [comment]
@buddhhu I can't change visibility of that repo as it is forked... but now have a look again at my forked repo if it is okay now? I tried my best to revert all stupid changes made by workflows... 🥲

**Comment by amitkr-codes** [comment]
@Gladiator-007 K it's better 👍

**Comment by Gladiator-007** [comment]
@buddhhu 😇😅

**Comment by New-dev0** [comment]
@Gladiator-007

**Comment by New-dev0** [comment]
@New-dev0

**Comment by New-dev0** [comment]
@New-dev0

**Comment by New-dev0** [comment]
@New-dev0

**Comment by New-dev0** [comment]
@New-dev0

**Comment by New-dev0** [comment]
@New-dev0 <b><i><u>Hello</b></i></u>

**Comment by New-dev0** [comment]
@New-dev0

**Comment by New-dev0** [comment]
@New-dev0 <h1><b>Join <a href="https://t.me/Telegram">Telegram</a></h1></b>

**Pull request closed without merging**
