### PR TITLE
Update youtube.py

### PR DESCRIPTION
**Pull request by MalinrRuwan**
I think this is how it should be changed. But please make this edit because iOS and Desktop versions cannot play mp3 in telegram. So it should opened in VLC or another player. Please make it to upload in m4a so the problem would sort out 🥇

### CODE REVIEW

**Comment by amitkr-codes** [comment]
MP3 format of audio is just universally supported, isn't it supported in iOS?

**Comment by MalinrRuwan** [comment]
Nope. MP3 cannot be played inside the iOS telegram app and Desktop. So it should be opened in a different app to be played. it makes the native telegram music player useless.

**Comment by amitkr-codes** [comment]
@MalinrRuwan Is MP3 format supported by iOS?

**Comment by MalinrRuwan** [comment]
iOS indeed support  MP3. but native telegram app does not. So it cannot be played from telegram.

**Comment by SpEcHiDe** [comment]
Renaming MP3 to M4A does not change the codec of the container 😂😂

#CAADAgAD6Q8AApeq8ElBetaXQiTAfgI

**Pull request merged**
