### PR TITLE
Please add this plugin or please give me rights to install this plugin it's made by me I made userbot to use this plugin

### PR DESCRIPTION
**Pull request by ghost**
#betting_game

[This is the plugin](https://t.me/UltroidSupport/25505)

### CODE REVIEW

**Comment by maxprogrammer007** [comment]
bro u should have PRed in add ons  repo

**Comment by ghost** [comment]
> bro u should have PRed in add ons repo

Means ?

**Comment by ProgrammingError** [comment]
Test

**Comment by ProgrammingError** [comment]
Ntg

**Comment by 1Danish-00** [comment]
On addons

**Comment by TechiError** [comment]
On Addons

**Comment by ghost** [comment]
> On addons

Means

**Pull request closed without merging**
