### PR TITLE
UltroidCli Build Fail Fix

### PR DESCRIPTION
**Pull request by iAkashPattnaik**
All the UltroidCli builds are failing because whenever they restart, i got what's exactly happening, heroku is taking the Dockerfile in Ultroid repo and not from UltroidCliTemplate repo... These have completely different commands, thus conflict exists!

Deleting Dockerfile will resolve it! Heroku isn't going to un-blacklist Ultroid anytime soon!

### CODE REVIEW

**Comment by iAkashPattnaik** [comment]
This only happens on update or manual restarts, auto restarts works fine...

image
image

**Comment by New-dev0** [comment]
@BLUE-DEVIL1134 Removing Dockerfile can't be considered as correct solution.
Since, Manual Deploy and some platform Still works for Repository.


Have you tried changing Workdir in CliTemplate Repo, does doing that works?

**Comment by iAkashPattnaik** [comment]
Never mind, i fixed it in ultroidcli itself, it will delete the `Dockerfile` after clone in `heroku` command only...
Will be released in a few mins!

**Comment by New-dev0** [comment]
@BLUE-DEVIL1134 Then This issue can be closed right? 
Thanks for maintaining Ultroid-Cli

**Comment by iAkashPattnaik** [comment]
> @BLUE-DEVIL1134 Then This issue can be closed right? Thanks for maintaining Ultroid-Cli

yeah, thats all i can do after getting kicked from TeamUltroid! :heart:

**Comment by amitkr-codes** [comment]
@BLUE-DEVIL1134 I guess, you were kicked because of your behaviour 🧐

**Comment by iAkashPattnaik** [comment]
ik that, no need to disclose that, atleast let me defame `Ultroid` in peace!

**Comment by amitkr-codes** [comment]
@BLUE-DEVIL1134

**Comment by amitkr-codes** [comment]
@buddhhu https://t.me/Ultroidspam/1168687

**Pull request closed without merging**
