### PR TITLE
Fixes v0.0.8.1

### PR DESCRIPTION
**Pull request by 1Danish-00**

### CODE REVIEW

**Comment by New-dev0** [comment]
@1Danish-00

**Comment by buddhhu** [comment]
@New-dev0

**Comment by buddhhu** [comment]
@buddhhu

**Comment by amitkr-codes** [comment]
@buddhhu

**Comment by amitkr-codes** [comment]
@buddhhu

**Comment by amitkr-codes** [comment]
@buddhhu

**Comment by amitkr-codes** [comment]
@buddhhu

**Comment by 1Danish-00** [comment]
@New-dev0

**Comment by New-dev0** [comment]
@1Danish-00

**Pull request merged**
