### PR TITLE
ffmpeg & mediainfo

### PR DESCRIPTION
**Pull request by Blackxin**

### CODE REVIEW

**Comment by New-dev0** [comment]
ffmpeg and mediainfo are used from apt packages, and not python packages

**Comment by Blackxin** [comment]
but the ffmpeg and media info, its not correctly work

**Comment by New-dev0** [comment]
@Blackxin mediainfo, ffmpeg etc apt packages are installed for cloud users via Dockerfile
termux users or other local users, may need to install them seperately whenever they found it required.

**Comment by New-dev0** [comment]
@New-dev0 [In reply to Devesh Pal [Break<?]]
to not increase the unused packages if unused

**Pull request closed without merging**
