### PR TITLE
Translated strings to jp

### PR DESCRIPTION
**Pull request by Achu2234**
Translated strings to jp

### CODE REVIEW

**Comment by Achu2234** [comment]
@New-dev0 @BLUE-DEVIL1134 any string left plx to tell to me

**Comment by New-dev0** [comment]
@Achu2234 These 17 strings are missing in Japanese language
https://spaceb.in/eDDMNxtD

**Comment by Achu2234** [comment]
> @Achu2234 These 17 strings are missing in Japanese language https://spaceb.in/eDDMNxtD

thanks

**Comment by Achu2234** [comment]
I not seed that do i want to add that also

**Comment by New-dev0** [comment]
@Achu2234 It will be great if you can

**Comment by Achu2234** [comment]
https://spaceb.in/QZMNYGLf
hope done @New-dev0

**Comment by New-dev0** [comment]
@Achu2234 Include that in your pull request

that paste was given for telling missing strings.

**Comment by Achu2234** [comment]
> @Achu2234 Include that in your pull request
> 
> that paste was given for telling missing strings.

ok

**Comment by Achu2234** [comment]
> @Achu2234 Include that in your pull request
> 
> that paste was given for telling missing strings.

sir can u add it will be helpfull for me

thank you

**Review by iAkashPattnaik — APPROVED** [review]

**Comment by Achu2234** [comment]
thanks

**Review by New-dev0 — APPROVED** [review]

**Comment by Achu2234** [comment]
why not mergered sir @New-dev0

**Comment by Achu2234** [comment]
why not mergered sir @New-dev0

**Pull request merged**
