### PR TITLE
Beautify ._.

### PR DESCRIPTION
**Pull request by Purushottam-6668**
Just Aded Some Designs

### CODE REVIEW

**Review by Purushottam-6668 — COMMENTED** [review]
done now

**Review by Purushottam-6668 — COMMENTED** [review]
sorry i was forgot to add spaces

**Comment by buddhhu** [comment]
Needed?

**Comment by Purushottam-6668** [comment]
> Needed?

😪Krdo naa Sur me kahi aur thodi change kr rha 
Marathi  language jyada log use nhi krte hy. isi liye just mr.yml me changes kiye hy .

**Comment by BelgenOp** [comment]
I don't thing, design change should be made separately to one lang. It will be inconsistent work somewhere.

**Pull request closed without merging**
