### PR TITLE
Improved Dockerfile

### PR DESCRIPTION
**Pull request by Tejas61900**

### CODE REVIEW

**Comment by 1Danish-00** [comment]
@Tejas61900 Idk y but mostly wen i use
Copy . .
Heroku ban id

**Comment by Tejas61900** [comment]
> @Tejas61900 Idk y but mostly wen i use
> Copy . .
> Heroku ban id

Strange , we are justing copying all source to container (hoeruko)

**Comment by Tejas61900** [comment]
@1Danish-00 I am closing this PR then .

**Comment by 1Danish-00** [comment]
> > @Tejas61900 Idk y but mostly wen i use
> > Copy . .
> > Heroku ban id
> 
> Strange , we are justing copying all source to container (hoeruko)

Yup

**Pull request closed without merging**
