### PR TITLE
Updated Heroku Deploy Button Link

### PR DESCRIPTION
**Pull request by DevilMinati7**
Updated Heroku Deploy Button Link

### CODE REVIEW

**Comment by ArnabXD** [comment]
Heroku automatically detects the repo if it is public . [read here](https://devcenter.heroku.com/articles/heroku-button#using-an-implicit-template)
> If you’re embedding the button in a GitHub repository’s README file, Heroku will automatically infer the repository URL from the referer header when someone clicks on the button.

so this is not a problem/bug . Thanks for the PR btw

**Comment by DevilMinati7** [comment]
Nope It Didn't detect. I directly used ur link

**Comment by ArnabXD** [comment]
I tested just now and works fine . I think its your browser issue

**Comment by New-dev0** [comment]
> Nope It Didn't detect. I directly used ur link

Directly click the button dont copy paste

**Pull request closed without merging**
