### PR TITLE
Remove Railway (music bots are forbidden)

### PR DESCRIPTION
**Pull request by ghost**
Music bots are forbidden on Railway, so deploying Ultroid will just get the user banned.

### CODE REVIEW

**Comment by xditya** [comment]
`Music-bot` is an optional feature, one which stays inactive until a user turns it on, and not the one that this repo focuses on. The users who deploy on railway shall not use that feature, and incase they do, and too many get banned, we'd be removing the deploy button.
thanks :)

**Comment by ghost** [comment]
Better Add a feature to restrict VC whenever Deployed on Railway Better To Prevent Bans

**Comment by amitkr-codes** [comment]
@Noob-Stranger Kanger Alert 🆘❌
Go away

**Comment by Hobby-Dev-0** [comment]
Sed

**Pull request closed without merging**
