### PR TITLE
Bypassed telegram word limits

### PR DESCRIPTION
**Pull request by Sh1vam**

### CODE REVIEW

**Comment by sppidy** [comment]
Do You Wanna Cause Floodwaits ?

**Review by sppidy — COMMENTED** [review]
Bro this Will Cause Floodwaits !

if u are sure that it wont cause floodwaits i may merge

**Review by Sh1vam — COMMENTED** [review]
Tag all Now Can Tag All me in chatmbers

**Comment by sppidy** [comment]
> Tag all Now Can Tag All me in chatmbers

Ik But it will flood messages

**Comment by Sh1vam** [comment]
ask users

**Comment by Sh1vam** [comment]
take theis openion idc

**Comment by sppidy** [comment]
> ask users

uh But They are afffected with floodwaits

They Spam Support by showing errors

**Comment by Sh1vam** [comment]
no they wont get add ascyno sleep(0.5) sec

**Comment by Sh1vam** [comment]
if so

**Comment by sppidy** [comment]
Ok Edit It We Will Merge Soon

**Comment by Sh1vam** [comment]
k

**Review by Sh1vam — COMMENTED** [review]
floodawait solved

**Comment by sppidy** [comment]
> floodawait solved

ok will merge it soon

**Comment by Sh1vam** [comment]
ohk

**Review by iAkashPattnaik — CHANGES_REQUESTED** [review]
Um...Please change branch to beta,
The main branch will only be maintained by Dev's (us)
@sppidy , don't approve until it's beta branch

**Comment by Sh1vam** [comment]
> Um...Please change branch to beta,
> The main branch will only be maintained by Dev's (us)
> @sppidy , don't approve until it's beta branch

If U Want To Merge Than Merge Some Of  Your Bot Users Told So Me Created Both The Pull Now Its Your Prob 
second one is(https://github.com/TeamUltroid/Ultroid/pull/27)
Me Iz Out Of This U Got Some Error In My Code Tell I will Solve That Caues Both The Codes Are Tested  First Then I Created Pull

**Comment by xditya** [comment]
> > Um...Please change branch to beta,
> > The main branch will only be maintained by Dev's (us)
> > @sppidy , don't approve until it's beta branch
> 
> If U Want To Merge Than Merge Some Of Your Bot Users Told So Me Created Both The Pull Now Its Your Prob
> second one is(#27)
> Me Iz Out Of This U Got Some Error In My Code Tell I will Solve That Caues Both The Codes Are Tested First Then I Created Pull

None asked you to commit here. Dont be like you're doing someone big deed to us in ur busy moment. 

WE DO NOT WANT TO MERGE IT.

**Comment by Sh1vam** [comment]
> > > Um...Please change branch to beta,
> > > The main branch will only be maintained by Dev's (us)
> > > @sppidy , don't approve until it's beta branch
> > 
> > 
> > If U Want To Merge Than Merge Some Of Your Bot Users Told So Me Created Both The Pull Now Its Your Prob
> > second one is(#27)
> > Me Iz Out Of This U Got Some Error In My Code Tell I will Solve That Caues Both The Codes Are Tested First Then I Created Pull
> 
> None asked you to commit here. Dont be like you're doing someone big deed to us in ur busy moment.
> 
> WE DO NOT WANT TO MERGE IT.

lol i neber pretended such that as i said above u can do what u want

**Comment by iAkashPattnaik** [comment]
> Um...Please change branch to beta,
> The main branch will only be maintained by Dev's (us)
> @sppidy , don't approve until it's beta branch

Fuk, a small message created wur...

**Pull request closed without merging**
