### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by kaif-00z**

### CODE REVIEW

**Comment by New-dev0** [comment]
@kaif-00z Please move your pull request to addons repository.

**Comment by kaif-00z** [comment]
but gist is better option for pasting @New-dev0

**Comment by New-dev0** [comment]
@kaif-00z There are Already many commands that pastes to some site or image.

I didn't told that gist shouldn't be added.
It will be better, If it will be present in Addons.

**Comment by kaif-00z** [comment]
ok

**Comment by New-dev0** [comment]
Waiting for Pull Request to Addons.... :)

**Pull request closed without merging**
