### PR TITLE
🥱

### PR DESCRIPTION
**Pull request by kaif-00z**
30min m bahut kuch ho sakta h sur !

### CODE REVIEW

**Comment by amitkr-codes** [comment]
None of the rss feeds post their feeds every minutes.

If your new pr comes with this title, you will be blocked by organization.

**Comment by kaif-00z** [comment]
> None of the rss feeds post their feeds every minutes.
> 
> If your new pr comes with this title, you will be blocked by organization.

Thier are so many  feeds , which post in every min...


btw apse jada kam kar kuch hu m rss feed pe 🥱

**Comment by kaif-00z** [comment]
> None of the rss feeds post their feeds every minutes.
> 
> If your new pr comes with this title, you will be blocked by organization.

Thier are so many  feeds , which post in every min...

**Comment by New-dev0** [comment]
@kaif-00z Why?

asteroid going to hit earth within next 30 minutes? 
Or
Elon musk going to transfer his money to me? 
Or 
Me going to be the next prime minister?

**Comment by New-dev0** [comment]
@kaif-00z That is why There is db key for Rss delay
So that you modify that for yourself
And 1 minute isn't a good deal to look for

**Comment by kaif-00z** [comment]
> @kaif-00z That is why There is db key for Rss delay So that you modify that for yourself And 1 minute isn't a good deal to look for

as ur wish [🥱]

**Comment by amitkr-codes** [comment]
@kaif-00z https://telegra.ph/file/c36aa4564258f96fbff90.jpg

**Pull request closed without merging**
