### PR TITLE
add UltroidCli deploy option for heroku

### PR DESCRIPTION
**Pull request by iAkashPattnaik**

### CODE REVIEW

**Comment by 1Danish-00** [comment]
Better, Just Change Heroku deploy link from our Button.

Bcoz - ppl click deploy button without reading up/down

**Comment by iAkashPattnaik** [comment]
Done!

**Comment by 1Danish-00** [comment]
> Done!

High?

https://github.com/TeamUltroid/Ultroid/pull/209#issuecomment-970050856

**Comment by iAkashPattnaik** [comment]
oh wait, me missed it!

**Review by iAkashPattnaik — COMMENTED** [review]
Atleast add link to real "ultroidcli" project!

**Comment by New-dev0** [comment]
> Atleast add link to real "ultroidcli" project!

It's already exists in Deploy [lastest] method
Writing that back, makes no sense

**Review by iAkashPattnaik — COMMENTED** [review]
great!

**Comment by iAkashPattnaik** [comment]
> > Atleast add link to real "ultroidcli" project!
> 
> It's already exists in Deploy [lastest] method Writing that back, makes no sense

Lol, "makes no sense", isn't that the whole point of ultroid?

**Pull request merged**
