### PR TITLE
animation plugin successfully tested

### PR DESCRIPTION
**Pull request by maxprogrammer007**
this plugin is successfully tested by me on  ultroid  . want proofs contact me at @maxprogrammer007. this is animation plugin

### CODE REVIEW

**Comment by Divkix** [comment]
Open a Pull Request on the addons repo, not here.
This is main repo and no such plugins will be added here like this.

Addons repo:
https://github.com/TeamUltroid/UltroidAddons

**Comment by New-dev0** [comment]
Heya , Thanks for your Contribution
But it can be considered for add-ons repo

**Comment by ArnabXD** [comment]
Please , For ADDONS make pull request in [UltroidAddons](https://github.com/TeamUltroid/UltroidAddons) , we won't be merging Unnecessary/Fun plugins in Main Repo

**Comment by maxprogrammer007** [comment]
okay sorry !!

**Pull request closed without merging**
