### PR TITLE
IMDb Inline and PyPi Inline

### PR DESCRIPTION
**Pull request by ufoptg**
Added Final imdb inline and pypi inline for review and merge

### CODE REVIEW

**Comment by New-dev0** [comment]
Hey, can you please PR your changes to https://github.com/TeamUltroid/UltroidAddons/tree/main/inline

**Comment by New-dev0** [comment]
TeamUltroid/Ultroid is only for core and basic plugins, which are related to Telegram related features

**Comment by New-dev0** [comment]
same for the weather plugin, https://github.com/TeamUltroid/Ultroid/blob/93c68713b9b053d7e37ba13d60db0e99ebc62797/plugins/weather.py

**Comment by ufoptg** [comment]
> Hey, can you please PR your changes to https://github.com/TeamUltroid/UltroidAddons/tree/main/inline
Sure once I get home I'll do that. .

**Comment by ufoptg** [comment]
# PR MOVED

https://github.com/TeamUltroid/UltroidAddons/pull/127

**Pull request closed without merging**
