### PR TITLE
Rename .env.sample to sample.env

### PR DESCRIPTION
**Pull request by Alacardo**

### CODE REVIEW

**Comment by xditya** [comment]
no

**Comment by amitkr-codes** [comment]
@Alacardo Mtlb kuch bhi commit Krna h bc

**Comment by Alacardo** [comment]
Accha tera ho gaya sorry sorry

**Comment by Alacardo** [comment]
> @Alacardo Mtlb kuch bhi commit Krna h bc

Aree galti se hua hai jyada mc bc mat kar.

**Comment by buddhhu** [comment]
@Alacardo Mc bola hi nahi
Khud maan liya ki tu h?

**Comment by Alacardo** [comment]
> @Alacardo Mc bola hi nahi
> Khud maan liya ki tu h?

Haa teri maa ke sath kiya tha, isiliye tere liye hu .
Chal be chutiye kaam hai, khi aur gand mara.

**Comment by buddhhu** [comment]
@Alacardo Aja maar
Gand mein jhadu daal k mor ki tarah nachaunga

**Pull request closed without merging**
