### PR TITLE
Fix mis-understanding for UltroidCli

### PR DESCRIPTION
**Pull request by iAkashPattnaik**
Hmm, I forgot that [`UltroidCli`](https://github.com/BLUE-DEVIL1134/UltroidCli) works on both servers like `heroku`, `qovery`, `railway` and `localhost`.

### CODE REVIEW

**Comment by xditya** [comment]
Using that and deploying to railway would still be against their tos. No to railway for now 😕

**Comment by iAkashPattnaik** [comment]
Hah! I got a fix for that.<br>
Create a repo and use [`Dockerfile`].

In there (`Dockerfile`), use [`UltroidCli`](https://github.com/BLUE-DEVIL1134/UltroidCli) and it won't get banned 'cause there is no link of direct use. `Railway` only blacklisted the repo, not the project.

**Comment by xditya** [comment]
> Hah! I got a fix for that. Create a repo and use [`Dockerfile`].
> 
> In there (`Dockerfile`), use [`UltroidCli`](https://github.com/BLUE-DEVIL1134/UltroidCli) and it won't get banned 'cause there is no link of direct use. `Railway` only blacklisted the repo, not the project.

We do not intend on breaking tos.

**Comment by iAkashPattnaik** [comment]
You are breaking nothing, It's a loophole, not a violation to their `TOS` .<br>
Go watch `Scam 1992` first.

**Comment by amitkr-codes** [comment]
@BLUE-DEVIL1134 U meant loop hole in system?

**Comment by iAkashPattnaik** [comment]
loop hole in their TOS...

**Comment by iAkashPattnaik** [comment]
btw, @xditya this pr wasn't wrong ...?
It literally works on both - `remote servers` and `localhost`.

**Pull request closed without merging**
