### PR TITLE
Inline index fix

### PR DESCRIPTION
**Pull request by ufoptg**
Inline will now work on both PC and phone 

All inlines working Ive tested and checked

### CODE REVIEW

**Comment by New-dev0** [comment]
what does your changes fix?

**Comment by ufoptg** [comment]
IMG_20240517_154114_204
That's PC 

IMG_20240517_154110_666
That's before fix 


IMG_20240517_154103_636
And that is after

**Comment by ufoptg** [comment]
# PR MOVED

https://github.com/TeamUltroid/UltroidAddons/pull/127

But im not sure if these changes still need to be made to main

**Comment by ufoptg** [comment]
Deleted

**Pull request closed without merging**
